FROM centos:7

RUN yum install -y sudo cc-c++ make && \
curl -sL https://rpm.nodesource.com/setup_12.x | sudo  -E bash - && \
yum install -y nodejs && \
curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo && \
yum install -y yarn && \
npm install -g @angular/cli@8.3.20
